# Generated by Django 5.1 on 2024-08-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
    ]
